spring:
  profiles:
    active: docker  #dev para h2 e docker para postgreSQL
  jackson:
    deserialization:
      fail-on-unknown-properties: false

logging:
  level:
    com.jhops10.musicrequestapi: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000  # 24 horas